/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Products;
import model.dao.ProductDAO;

/**
 *
 * @author vinicius
 */
public class CadProducts extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadProducts
     */
    public CadProducts() {
        initComponents();
        read();
        DefaultTableModel model = (DefaultTableModel) jTableProd.getModel();
        jTableProd.setRowSorter(new TableRowSorter(model));
    }
    
    public void read(){
        DefaultTableModel model = (DefaultTableModel) jTableProd.getModel();
        ProductDAO pdao = new ProductDAO();
        model.setNumRows(0);
        pdao.read().forEach((p) -> {
            model.addRow(new Object[]{
                p.getId(),
                p.getDescription(),
                p.getPrice(),
                p.getQuantity()
            });
        });
    }
    
    public void search(String description){
        DefaultTableModel model = (DefaultTableModel) jTableProd.getModel();
        ProductDAO pdao = new ProductDAO();
        model.setNumRows(0);
        pdao.search(description).forEach((p) -> {
            model.addRow(new Object[]{
                p.getId(),
                p.getDescription(),
                p.getQuantity(),
                p.getPrice()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProdName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jProdPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnProdSave = new javax.swing.JButton();
        spnQuantity = new javax.swing.JSpinner();
        btnDeleteProd = new javax.swing.JButton();
        btnUpdateProd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProd = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Products");

        jLabel1.setText("Name:");

        jProdName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel2.setText("Price:");

        jLabel3.setText("US$");

        jProdPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProdPriceActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantity:");

        btnProdSave.setText("save");
        btnProdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdSaveActionPerformed(evt);
            }
        });

        spnQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQuantityStateChanged(evt);
            }
        });

        btnDeleteProd.setText("delete");
        btnDeleteProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProdActionPerformed(evt);
            }
        });

        btnUpdateProd.setText("update");
        btnUpdateProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProdActionPerformed(evt);
            }
        });

        jLabel5.setText("Search:");

        txtSearch.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnFind.setText("find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFind)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnProdSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateProd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDeleteProd)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFind))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpdateProd)
                        .addComponent(btnDeleteProd)
                        .addComponent(jLabel5)
                        .addComponent(btnProdSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "PRICE", "QUANTITY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProd);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jProdPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProdPriceActionPerformed
        
    }//GEN-LAST:event_jProdPriceActionPerformed

    private void btnProdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdSaveActionPerformed
        Products prod = new Products();
        ProductDAO pdao = new ProductDAO();
        prod.setDescription(jProdName.getText());
        prod.setQuantity((int) spnQuantity.getValue());
        prod.setPrice(Double.parseDouble(jProdPrice.getText()));
        pdao.create(prod);
        jProdName.setText(null);
        jProdPrice.setText(null);
        spnQuantity.setValue(1);
        read();
        
    }//GEN-LAST:event_btnProdSaveActionPerformed

    private void spnQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQuantityStateChanged
        
    }//GEN-LAST:event_spnQuantityStateChanged

    private void btnDeleteProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProdActionPerformed
        if(jTableProd.getSelectedRow() != -1){
            Products prod = new Products();
            ProductDAO pdao = new ProductDAO();
            
            prod.setId((int) jTableProd.getValueAt(jTableProd.getSelectedRow(), 0));
            pdao.delete(prod);
            
        }else{
            JOptionPane.showMessageDialog(null, "Select an item to delete");
        }
        jProdName.setText(null);
        jProdPrice.setText(null);
        spnQuantity.setValue(1);
        read();
    }//GEN-LAST:event_btnDeleteProdActionPerformed

    private void jTableProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdMouseClicked
        if(jTableProd.getSelectedRow() != -1){
            jProdName.setText(jTableProd.getValueAt(jTableProd.getSelectedRow(), 1).toString());
            jProdPrice.setText(jTableProd.getValueAt(jTableProd.getSelectedRow(), 2).toString());
            spnQuantity.setValue(jTableProd.getValueAt(jTableProd.getSelectedRow(), 3));
        } else{
            JOptionPane.showMessageDialog(null, "Select an item to Update.");
        }
    }//GEN-LAST:event_jTableProdMouseClicked

    private void btnUpdateProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProdActionPerformed
        if(jTableProd.getSelectedRow() != -1){
            Products prod = new Products();
            ProductDAO pdao = new ProductDAO();
            
            prod.setId((int) jTableProd.getValueAt(jTableProd.getSelectedRow(), 0));
            prod.setDescription(jProdName.getText());
            prod.setQuantity((int) spnQuantity.getValue());
            prod.setPrice(Double.parseDouble(jProdPrice.getText()));
            
            pdao.update(prod);
            
        } else{
            JOptionPane.showMessageDialog(null, "Select an item to Update.");
        } 
        
        jProdName.setText(null);
        jProdPrice.setText(null);
        spnQuantity.setValue(1);
        read();
    }//GEN-LAST:event_btnUpdateProdActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        search(txtSearch.getText());
    }//GEN-LAST:event_btnFindActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteProd;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnProdSave;
    private javax.swing.JButton btnUpdateProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jProdName;
    private javax.swing.JTextField jProdPrice;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableProd;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
