/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author vinicius
 */
public class PrincipalMDI extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalMDI
     */
    public PrincipalMDI() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFile = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jUser = new javax.swing.JMenu();
        jUserNew = new javax.swing.JMenuItem();
        jUserUpdt = new javax.swing.JMenuItem();
        jUserDlt = new javax.swing.JMenuItem();
        jUserSch = new javax.swing.JMenuItem();
        jClient = new javax.swing.JMenu();
        jClientCreate = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        CreateMenu = new javax.swing.JMenuItem();
        ReadMenu = new javax.swing.JMenuItem();
        jAbout = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        jFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/files-icon.png"))); // NOI18N
        jFile.setText("File");

        jMenuItem10.setText("Back");
        jFile.add(jMenuItem10);

        jMenuBar1.add(jFile);

        jUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-icon.png"))); // NOI18N
        jUser.setText("Users");

        jUserNew.setText("New");
        jUserNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserNewActionPerformed(evt);
            }
        });
        jUser.add(jUserNew);

        jUserUpdt.setText("Updtade");
        jUser.add(jUserUpdt);

        jUserDlt.setText("Delete");
        jUser.add(jUserDlt);

        jUserSch.setText("Search");
        jUser.add(jUserSch);

        jMenuBar1.add(jUser);

        jClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/client-icon.png"))); // NOI18N
        jClient.setText("Clients");

        jClientCreate.setText("Create");
        jClientCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientCreateActionPerformed(evt);
            }
        });
        jClient.add(jClientCreate);

        jMenuItem7.setText("Update");
        jClient.add(jMenuItem7);

        jMenuItem8.setText("Delete");
        jClient.add(jMenuItem8);

        jMenuItem9.setText("Search");
        jClient.add(jMenuItem9);

        jMenuBar1.add(jClient);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product-icon.png"))); // NOI18N
        jMenu1.setText("Products");

        CreateMenu.setText("Manage");
        CreateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateMenuActionPerformed(evt);
            }
        });
        jMenu1.add(CreateMenu);

        ReadMenu.setText("Read");
        ReadMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadMenuActionPerformed(evt);
            }
        });
        jMenu1.add(ReadMenu);

        jMenuBar1.add(jMenu1);

        jAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coffee-icon.png"))); // NOI18N
        jAbout.setText("About");

        jMenuItem5.setText("Creation");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jAbout.add(jMenuItem5);

        jMenuBar1.add(jAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUserNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserNewActionPerformed
        // TODO add your handling code here:
        TelaCadastroUser telaCadUser = new TelaCadastroUser();
        jDesktopPane1.add(telaCadUser);
        telaCadUser.setVisible(true);
        
    }//GEN-LAST:event_jUserNewActionPerformed

    private void jClientCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientCreateActionPerformed
        // TODO add your handling code here:
        CadClient tlCadClient = new CadClient();
        jDesktopPane1.add(tlCadClient);
        tlCadClient.setVisible(true);
    }//GEN-LAST:event_jClientCreateActionPerformed

    private void CreateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateMenuActionPerformed
        CadProducts tlCadProd = new CadProducts();
        jDesktopPane1.add(tlCadProd);
        tlCadProd.setVisible(true);
    }//GEN-LAST:event_CreateMenuActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CreatingFileChooser tlFileChooser = new CreatingFileChooser();
        jDesktopPane1.add(tlFileChooser);
        tlFileChooser.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void ReadMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadMenuActionPerformed
        ReadProducts tlReadProd = new ReadProducts();
        jDesktopPane1.add(tlReadProd);
        tlReadProd.setVisible(true);
    }//GEN-LAST:event_ReadMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CreateMenu;
    private javax.swing.JMenuItem ReadMenu;
    private javax.swing.JMenu jAbout;
    private javax.swing.JMenu jClient;
    private javax.swing.JMenuItem jClientCreate;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jFile;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jUser;
    private javax.swing.JMenuItem jUserDlt;
    private javax.swing.JMenuItem jUserNew;
    private javax.swing.JMenuItem jUserSch;
    private javax.swing.JMenuItem jUserUpdt;
    // End of variables declaration//GEN-END:variables
}
