/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Products;
import model.dao.ProductDAO;

/**
 *
 * @author vinicius
 */
public class ReadProducts extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReadProducts
     */
    public ReadProducts() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) jTableProd.getModel();
        jTableProd.setRowSorter(new TableRowSorter(model));
        read();
        
        ProductDAO cbDAO = new ProductDAO();
        for(Products pCB: cbDAO.read()){
            cbProducts.addItem(pCB);
        }
        
    }
    
    public void read(){
        DefaultTableModel model = (DefaultTableModel) jTableProd.getModel();
        ProductDAO pdao = new ProductDAO();
        model.setNumRows(0);
        pdao.read().forEach((p) -> {
            model.addRow(new Object[]{
                p.getId(),
                p.getDescription(),
                p.getQuantity(),
                p.getPrice()
            });
        });
    }
    
    
    public void search(String description){
        DefaultTableModel model = (DefaultTableModel) jTableProd.getModel();
        ProductDAO pdao = new ProductDAO();
        model.setNumRows(0);
        pdao.search(description).forEach((p) -> {
            model.addRow(new Object[]{
                p.getId(),
                p.getDescription(),
                p.getQuantity(),
                p.getPrice()
            });
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProd = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        cbProducts = new javax.swing.JComboBox<>();
        btnGetCB = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setForeground(new java.awt.Color(0, 102, 153));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Products");

        jScrollPane1.setForeground(new java.awt.Color(0, 102, 153));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTableProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "QUANTITY", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProd);
        if (jTableProd.getColumnModel().getColumnCount() > 0) {
            jTableProd.getColumnModel().getColumn(0).setHeaderValue("ID");
            jTableProd.getColumnModel().getColumn(1).setHeaderValue("NAME");
            jTableProd.getColumnModel().getColumn(2).setHeaderValue("QUANTITY");
            jTableProd.getColumnModel().getColumn(3).setHeaderValue("PRICE");
        }

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Search:");

        txtSearch.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnFind.setText("find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnGetCB.setText("ok");
        btnGetCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch)
                        .addGap(12, 12, 12)
                        .addComponent(btnFind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGetCB)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind)
                    .addComponent(cbProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetCB))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdMouseClicked
        
    }//GEN-LAST:event_jTableProdMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        search(txtSearch.getText());
        
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnGetCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetCBActionPerformed
        // TODO add your handling code here:
        Products prod = (Products) cbProducts.getSelectedItem();
        JOptionPane.showMessageDialog(null, "Id: " + prod.getId() 
                + "\nDesc: " + prod.getDescription()
                + "\nQuantity: " + prod.getQuantity()
                + "\nPrice: " + prod.getPrice());
        
    }//GEN-LAST:event_btnGetCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnGetCB;
    private javax.swing.JComboBox<Object> cbProducts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProd;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
